/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EbookMakerImport } from './routes/ebook-maker'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const EbookMakerRoute = EbookMakerImport.update({
  id: '/ebook-maker',
  path: '/ebook-maker',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ebook-maker': {
      id: '/ebook-maker'
      path: '/ebook-maker'
      fullPath: '/ebook-maker'
      preLoaderRoute: typeof EbookMakerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ebook-maker': typeof EbookMakerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ebook-maker': typeof EbookMakerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ebook-maker': typeof EbookMakerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ebook-maker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ebook-maker'
  id: '__root__' | '/' | '/ebook-maker'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EbookMakerRoute: typeof EbookMakerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EbookMakerRoute: EbookMakerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ebook-maker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ebook-maker": {
      "filePath": "ebook-maker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
