/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BrettappsdevappImport } from './routes/brettappsdevapp'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BrettappsdevappRoute = BrettappsdevappImport.update({
  id: '/brettappsdevapp',
  path: '/brettappsdevapp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/brettappsdevapp': {
      id: '/brettappsdevapp'
      path: '/brettappsdevapp'
      fullPath: '/brettappsdevapp'
      preLoaderRoute: typeof BrettappsdevappImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brettappsdevapp': typeof BrettappsdevappRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brettappsdevapp': typeof BrettappsdevappRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/brettappsdevapp': typeof BrettappsdevappRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brettappsdevapp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brettappsdevapp'
  id: '__root__' | '/' | '/brettappsdevapp'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrettappsdevappRoute: typeof BrettappsdevappRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrettappsdevappRoute: BrettappsdevappRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/brettappsdevapp"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/brettappsdevapp": {
      "filePath": "brettappsdevapp.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
